name: Build and Release CLI

on:
  push:
    tags:
      - "*"

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "::add-path::${HOME}/.bun/bin"

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/hdz
          body: |
            This release was generated automatically.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
